/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class End
    extends Token {

  public End(int line, int pos) {
    super("", line, pos);
  }

  @Override
  public Type getType() {
    return Type.TEnd;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.TEnd;
  }
}
