/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NArray
    extends Node {

  private final int line;
  private final int pos;
  private final NRt eRt;
  private final N$26 e$26;
  private final NImmediate eImmediate;
  private final N$37 e$37;
  private final NRs eRs;
  private final N$38 e$38;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inArray(this);
    walker.caseArray(this);
    walker.outArray(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eRt.apply(walker);
    this.e$26.apply(walker);
    this.eImmediate.apply(walker);
    this.e$37.apply(walker);
    this.eRs.apply(walker);
    this.e$38.apply(walker);
  }

  NArray(int line, int pos, NRt pRt, N$26 p$26, NImmediate pImmediate, N$37 p$37, NRs pRs, N$38 p$38) {
    this.line = line;
    this.pos = pos;
    this.eRt = pRt;
    this.e$26 = p$26;
    this.eImmediate = pImmediate;
    this.e$37 = p$37;
    this.eRs = pRs;
    this.e$38 = p$38;
  }

  @Override
  public Type getType() {
    return Type.T_Array;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Array;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Array;
  }

  public NRt get_Rt() {
    return this.eRt;
  }

  public NImmediate get_Immediate() {
    return this.eImmediate;
  }

  public NRs get_Rs() {
    return this.eRs;
  }

  NRt internalGetRt() {
    return this.eRt;
  }

  N$26 internalGet$26() {
    return this.e$26;
  }

  NImmediate internalGetImmediate() {
    return this.eImmediate;
  }

  N$37 internalGet$37() {
    return this.e$37;
  }

  NRs internalGetRs() {
    return this.eRs;
  }

  N$38 internalGet$38() {
    return this.e$38;
  }
}
