/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NArray
    extends Node {

  private final int line;
  private final int pos;
  private final NRt eRt;
  private final N$20 e$20;
  private final NNumber eNumber;
  private final N$44 e$44;
  private final NRs eRs;
  private final N$45 e$45;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inArray(this);
    walker.caseArray(this);
    walker.outArray(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eRt.apply(walker);
    this.e$20.apply(walker);
    this.eNumber.apply(walker);
    this.e$44.apply(walker);
    this.eRs.apply(walker);
    this.e$45.apply(walker);
  }

  NArray(int line, int pos, NRt pRt, N$20 p$20, NNumber pNumber, N$44 p$44, NRs pRs, N$45 p$45) {
    this.line = line;
    this.pos = pos;
    this.eRt = pRt;
    this.e$20 = p$20;
    this.eNumber = pNumber;
    this.e$44 = p$44;
    this.eRs = pRs;
    this.e$45 = p$45;
  }

  @Override
  public Type getType() {
    return Type.T_Array;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Array;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Array;
  }

  public NRt get_Rt() {
    return this.eRt;
  }

  public NNumber get_Number() {
    return this.eNumber;
  }

  public NRs get_Rs() {
    return this.eRs;
  }

  NRt internalGetRt() {
    return this.eRt;
  }

  N$20 internalGet$20() {
    return this.e$20;
  }

  NNumber internalGetNumber() {
    return this.eNumber;
  }

  N$44 internalGet$44() {
    return this.e$44;
  }

  NRs internalGetRs() {
    return this.eRs;
  }

  N$45 internalGet$45() {
    return this.e$45;
  }
}
