/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NCommonDatas_Many
    extends NCommonDatas {

  private final int line;
  private final int pos;
  private final NCommonData eCommonData;
  private final NCommonDatas eCommonDatas;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inCommonDatas_Many(this);
    walker.caseCommonDatas_Many(this);
    walker.outCommonDatas_Many(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eCommonData.apply(walker);
    this.eCommonDatas.apply(walker);
  }

  public NCommonDatas_Many(int line, int pos, NCommonData pCommonData, NCommonDatas pCommonDatas) {
    this.line = line;
    this.pos = pos;
    this.eCommonData = pCommonData;
    this.eCommonDatas = pCommonDatas;
  }

  @Override
  public Type getType() {
    return Type.T_CommonDatas_Many;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_CommonDatas;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_CommonDatas_Many;
  }

  public NCommonData get_CommonData() {
    return this.eCommonData;
  }

  public NCommonDatas get_CommonDatas() {
    return this.eCommonDatas;
  }

  NCommonData internalGetCommonData() {
    return this.eCommonData;
  }

  NCommonDatas internalGetCommonDatas() {
    return this.eCommonDatas;
  }
}
