/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NCommonData_Byte
    extends NCommonData {

  private final int line;
  private final int pos;
  private final N$48 e$48;
  private final NDirectivesQtes eDirectivesQtes;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inCommonData_Byte(this);
    walker.caseCommonData_Byte(this);
    walker.outCommonData_Byte(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$48.apply(walker);
    this.eDirectivesQtes.apply(walker);
  }

  NCommonData_Byte(int line, int pos, N$48 p$48, NDirectivesQtes pDirectivesQtes) {
    this.line = line;
    this.pos = pos;
    this.e$48 = p$48;
    this.eDirectivesQtes = pDirectivesQtes;
  }

  @Override
  public Type getType() {
    return Type.T_CommonData_Byte;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_CommonData;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_CommonData_Byte;
  }

  public NDirectivesQtes get_DirectivesQtes() {
    return this.eDirectivesQtes;
  }

  N$48 internalGet$48() {
    return this.e$48;
  }

  NDirectivesQtes internalGetDirectivesQtes() {
    return this.eDirectivesQtes;
  }
}
