/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NCommonData_Ascii
    extends NCommonData {

  private final int line;
  private final int pos;
  private final N$49 e$49;
  private final NConsoleString eConsoleString;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inCommonData_Ascii(this);
    walker.caseCommonData_Ascii(this);
    walker.outCommonData_Ascii(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$49.apply(walker);
    this.eConsoleString.apply(walker);
  }

  NCommonData_Ascii(int line, int pos, N$49 p$49, NConsoleString pConsoleString) {
    this.line = line;
    this.pos = pos;
    this.e$49 = p$49;
    this.eConsoleString = pConsoleString;
  }

  @Override
  public Type getType() {
    return Type.T_CommonData_Ascii;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_CommonData;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_CommonData_Ascii;
  }

  public NConsoleString get_ConsoleString() {
    return this.eConsoleString;
  }

  N$49 internalGet$49() {
    return this.e$49;
  }

  NConsoleString internalGetConsoleString() {
    return this.eConsoleString;
  }
}
