/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NCommonData_Lbl
    extends NCommonData {

  private final int line;
  private final int pos;
  private final NString eString;
  private final N$55 e$55;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inCommonData_Lbl(this);
    walker.caseCommonData_Lbl(this);
    walker.outCommonData_Lbl(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eString.apply(walker);
    this.e$55.apply(walker);
  }

  NCommonData_Lbl(int line, int pos, NString pString, N$55 p$55) {
    this.line = line;
    this.pos = pos;
    this.eString = pString;
    this.e$55 = p$55;
  }

  @Override
  public Type getType() {
    return Type.T_CommonData_Lbl;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_CommonData;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_CommonData_Lbl;
  }

  public NString get_String() {
    return this.eString;
  }

  NString internalGetString() {
    return this.eString;
  }

  N$55 internalGet$55() {
    return this.e$55;
  }
}
