/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NCommonData_Word
    extends NCommonData {

  private final int line;
  private final int pos;
  private final N$46 e$46;
  private final NDirectivesQtes eDirectivesQtes;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inCommonData_Word(this);
    walker.caseCommonData_Word(this);
    walker.outCommonData_Word(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$46.apply(walker);
    this.eDirectivesQtes.apply(walker);
  }

  NCommonData_Word(int line, int pos, N$46 p$46, NDirectivesQtes pDirectivesQtes) {
    this.line = line;
    this.pos = pos;
    this.e$46 = p$46;
    this.eDirectivesQtes = pDirectivesQtes;
  }

  @Override
  public Type getType() {
    return Type.T_CommonData_Word;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_CommonData;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_CommonData_Word;
  }

  public NDirectivesQtes get_DirectivesQtes() {
    return this.eDirectivesQtes;
  }

  N$46 internalGet$46() {
    return this.e$46;
  }

  NDirectivesQtes internalGetDirectivesQtes() {
    return this.eDirectivesQtes;
  }
}
