/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NConsoleString
    extends Token {

  public NConsoleString(String text, int line, int pos) {
    super(text, line, pos);
  }

  @Override
  public Type getType() {
    return Type.T_ConsoleString;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_ConsoleString;
  }

  @Override
  public void apply(Walker walker) {
    walker.inConsoleString(this);
    walker.caseConsoleString(this);
    walker.outConsoleString(this);
  }
}
