/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NDirectivesQte_Dirqt
    extends NDirectivesQte {

  private final int line;
  private final int pos;
  private final NNumber eNumber;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inDirectivesQte_Dirqt(this);
    walker.caseDirectivesQte_Dirqt(this);
    walker.outDirectivesQte_Dirqt(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eNumber.apply(walker);
  }

  public NDirectivesQte_Dirqt(int line, int pos, NNumber pNumber) {
    this.line = line;
    this.pos = pos;
    this.eNumber = pNumber;
  }

  @Override
  public Type getType() {
    return Type.T_DirectivesQte_Dirqt;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_DirectivesQte;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_DirectivesQte_Dirqt;
  }

  public NNumber get_Number() {
    return this.eNumber;
  }

  NNumber internalGetNumber() {
    return this.eNumber;
  }
}
