/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class NDirectivesQtes_$1
    extends NDirectivesQtes {

  private final int line;
  private final int pos;
  private final NDirectivesQte eDirectivesQte;
  private final N$20 e$20;
  private final NDirectivesQtes eDirectivesQtes;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.defaultIn(this);
    walker.defaultCase(this);
    walker.defaultOut(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eDirectivesQte.apply(walker);
    this.e$20.apply(walker);
    this.eDirectivesQtes.apply(walker);
  }

  NDirectivesQtes_$1(int line, int pos, NDirectivesQte pDirectivesQte, N$20 p$20, NDirectivesQtes pDirectivesQtes) {
    this.line = line;
    this.pos = pos;
    this.eDirectivesQte = pDirectivesQte;
    this.e$20 = p$20;
    this.eDirectivesQtes = pDirectivesQtes;
  }

  @Override
  public Type getType() {
    return Type.TAnonymous;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_DirectivesQtes;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_DirectivesQtes_$1;
  }

  NDirectivesQte internalGetDirectivesQte() {
    return this.eDirectivesQte;
  }

  N$20 internalGet$20() {
    return this.e$20;
  }

  NDirectivesQtes internalGetDirectivesQtes() {
    return this.eDirectivesQtes;
  }
}
