/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NImmediate_Unsigned
    extends NImmediate {

  private final int line;
  private final int pos;
  private final NNumberu eNumberu;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inImmediate_Unsigned(this);
    walker.caseImmediate_Unsigned(this);
    walker.outImmediate_Unsigned(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eNumberu.apply(walker);
  }

  public NImmediate_Unsigned(int line, int pos, NNumberu pNumberu) {
    this.line = line;
    this.pos = pos;
    this.eNumberu = pNumberu;
  }

  @Override
  public Type getType() {
    return Type.T_Immediate_Unsigned;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Immediate;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Immediate_Unsigned;
  }

  public NNumberu get_Numberu() {
    return this.eNumberu;
  }

  NNumberu internalGetNumberu() {
    return this.eNumberu;
  }
}
