/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NImmediate_Signed
    extends NImmediate {

  private final int line;
  private final int pos;
  private final NNumber eNumber;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inImmediate_Signed(this);
    walker.caseImmediate_Signed(this);
    walker.outImmediate_Signed(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eNumber.apply(walker);
  }

  public NImmediate_Signed(int line, int pos, NNumber pNumber) {
    this.line = line;
    this.pos = pos;
    this.eNumber = pNumber;
  }

  @Override
  public Type getType() {
    return Type.T_Immediate_Signed;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Immediate;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Immediate_Signed;
  }

  public NNumber get_Number() {
    return this.eNumber;
  }

  NNumber internalGetNumber() {
    return this.eNumber;
  }
}
