/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NJmpExpr_Lbl
    extends NJmpExpr {

  private final int line;
  private final int pos;
  private final NAddress eAddress;
  private final N$18 e$18;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inJmpExpr_Lbl(this);
    walker.caseJmpExpr_Lbl(this);
    walker.outJmpExpr_Lbl(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eAddress.apply(walker);
    this.e$18.apply(walker);
  }

  NJmpExpr_Lbl(int line, int pos, NAddress pAddress, N$18 p$18) {
    this.line = line;
    this.pos = pos;
    this.eAddress = pAddress;
    this.e$18 = p$18;
  }

  @Override
  public Type getType() {
    return Type.T_JmpExpr_Lbl;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_JmpExpr;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_JmpExpr_Lbl;
  }

  public NAddress get_Address() {
    return this.eAddress;
  }

  NAddress internalGetAddress() {
    return this.eAddress;
  }

  N$18 internalGet$18() {
    return this.e$18;
  }
}
