/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NNumberu
    extends Token {

  public NNumberu(String text, int line, int pos) {
    super(text, line, pos);
  }

  @Override
  public Type getType() {
    return Type.T_Numberu;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Numberu;
  }

  @Override
  public void apply(Walker walker) {
    walker.inNumberu(this);
    walker.caseNumberu(this);
    walker.outNumberu(this);
  }
}
