/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NNumber
    extends Token {

  public NNumber(String text, int line, int pos) {
    super(text, line, pos);
  }

  @Override
  public Type getType() {
    return Type.T_Number;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Number;
  }

  @Override
  public void apply(Walker walker) {
    walker.inNumber(this);
    walker.caseNumber(this);
    walker.outNumber(this);
  }
}
