/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NRegister
    extends Token {

  public NRegister(String text, int line, int pos) {
    super(text, line, pos);
  }

  @Override
  public Type getType() {
    return Type.T_Register;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Register;
  }

  @Override
  public void apply(Walker walker) {
    walker.inRegister(this);
    walker.caseRegister(this);
    walker.outRegister(this);
  }
}
