/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NRegExpr
    extends Node {

  private final int line;
  private final int pos;
  private final NRd eRd;
  private final N$26 e$26$1;
  private final NRs eRs;
  private final N$26 e$26$2;
  private final NRt eRt;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inRegExpr(this);
    walker.caseRegExpr(this);
    walker.outRegExpr(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eRd.apply(walker);
    this.e$26$1.apply(walker);
    this.eRs.apply(walker);
    this.e$26$2.apply(walker);
    this.eRt.apply(walker);
  }

  NRegExpr(int line, int pos, NRd pRd, N$26 p$26$1, NRs pRs, N$26 p$26$2, NRt pRt) {
    this.line = line;
    this.pos = pos;
    this.eRd = pRd;
    this.e$26$1 = p$26$1;
    this.eRs = pRs;
    this.e$26$2 = p$26$2;
    this.eRt = pRt;
  }

  @Override
  public Type getType() {
    return Type.T_RegExpr;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_RegExpr;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_RegExpr;
  }

  public NRd get_Rd() {
    return this.eRd;
  }

  public NRs get_Rs() {
    return this.eRs;
  }

  public NRt get_Rt() {
    return this.eRt;
  }

  NRd internalGetRd() {
    return this.eRd;
  }

  N$26 internalGet$26$1() {
    return this.e$26$1;
  }

  NRs internalGetRs() {
    return this.eRs;
  }

  N$26 internalGet$26$2() {
    return this.e$26$2;
  }

  NRt internalGetRt() {
    return this.eRt;
  }
}
