/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NStmt_Sc
    extends NStmt {

  private final int line;
  private final int pos;
  private final N$27 e$27;
  private final NImmExpr eImmExpr;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inStmt_Sc(this);
    walker.caseStmt_Sc(this);
    walker.outStmt_Sc(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$27.apply(walker);
    this.eImmExpr.apply(walker);
  }

  NStmt_Sc(int line, int pos, N$27 p$27, NImmExpr pImmExpr) {
    this.line = line;
    this.pos = pos;
    this.e$27 = p$27;
    this.eImmExpr = pImmExpr;
  }

  @Override
  public Type getType() {
    return Type.T_Stmt_Sc;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmt;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmt_Sc;
  }

  public NImmExpr get_ImmExpr() {
    return this.eImmExpr;
  }

  N$27 internalGet$27() {
    return this.e$27;
  }

  NImmExpr internalGetImmExpr() {
    return this.eImmExpr;
  }
}
