/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NStmt_La
    extends NStmt {

  private final int line;
  private final int pos;
  private final N$42 e$42;
  private final NRegister eRegister;
  private final N$20 e$20;
  private final NString eString;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inStmt_La(this);
    walker.caseStmt_La(this);
    walker.outStmt_La(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$42.apply(walker);
    this.eRegister.apply(walker);
    this.e$20.apply(walker);
    this.eString.apply(walker);
  }

  NStmt_La(int line, int pos, N$42 p$42, NRegister pRegister, N$20 p$20, NString pString) {
    this.line = line;
    this.pos = pos;
    this.e$42 = p$42;
    this.eRegister = pRegister;
    this.e$20 = p$20;
    this.eString = pString;
  }

  @Override
  public Type getType() {
    return Type.T_Stmt_La;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmt;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmt_La;
  }

  public NRegister get_Register() {
    return this.eRegister;
  }

  public NString get_String() {
    return this.eString;
  }

  N$42 internalGet$42() {
    return this.e$42;
  }

  NRegister internalGetRegister() {
    return this.eRegister;
  }

  N$20 internalGet$20() {
    return this.e$20;
  }

  NString internalGetString() {
    return this.eString;
  }
}
