/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NStmt_Sub
    extends NStmt {

  private final int line;
  private final int pos;
  private final N$4 e$4;
  private final NRegExpr eRegExpr;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inStmt_Sub(this);
    walker.caseStmt_Sub(this);
    walker.outStmt_Sub(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$4.apply(walker);
    this.eRegExpr.apply(walker);
  }

  NStmt_Sub(int line, int pos, N$4 p$4, NRegExpr pRegExpr) {
    this.line = line;
    this.pos = pos;
    this.e$4 = p$4;
    this.eRegExpr = pRegExpr;
  }

  @Override
  public Type getType() {
    return Type.T_Stmt_Sub;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmt;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmt_Sub;
  }

  public NRegExpr get_RegExpr() {
    return this.eRegExpr;
  }

  N$4 internalGet$4() {
    return this.e$4;
  }

  NRegExpr internalGetRegExpr() {
    return this.eRegExpr;
  }
}
