/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NStmt_Srl
    extends NStmt {

  private final int line;
  private final int pos;
  private final N$18 e$18;
  private final NShift eShift;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inStmt_Srl(this);
    walker.caseStmt_Srl(this);
    walker.outStmt_Srl(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$18.apply(walker);
    this.eShift.apply(walker);
  }

  NStmt_Srl(int line, int pos, N$18 p$18, NShift pShift) {
    this.line = line;
    this.pos = pos;
    this.e$18 = p$18;
    this.eShift = pShift;
  }

  @Override
  public Type getType() {
    return Type.T_Stmt_Srl;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmt;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmt_Srl;
  }

  public NShift get_Shift() {
    return this.eShift;
  }

  N$18 internalGet$18() {
    return this.e$18;
  }

  NShift internalGetShift() {
    return this.eShift;
  }
}
