/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NStmt_Lw
    extends NStmt {

  private final int line;
  private final int pos;
  private final N$25 e$25;
  private final NImmExpr eImmExpr;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inStmt_Lw(this);
    walker.caseStmt_Lw(this);
    walker.outStmt_Lw(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$25.apply(walker);
    this.eImmExpr.apply(walker);
  }

  NStmt_Lw(int line, int pos, N$25 p$25, NImmExpr pImmExpr) {
    this.line = line;
    this.pos = pos;
    this.e$25 = p$25;
    this.eImmExpr = pImmExpr;
  }

  @Override
  public Type getType() {
    return Type.T_Stmt_Lw;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmt;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmt_Lw;
  }

  public NImmExpr get_ImmExpr() {
    return this.eImmExpr;
  }

  N$25 internalGet$25() {
    return this.e$25;
  }

  NImmExpr internalGetImmExpr() {
    return this.eImmExpr;
  }
}
