/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NStmt_Jmpreg
    extends NStmt {

  private final int line;
  private final int pos;
  private final N$32 e$32;
  private final NRegister eRegister;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inStmt_Jmpreg(this);
    walker.caseStmt_Jmpreg(this);
    walker.outStmt_Jmpreg(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$32.apply(walker);
    this.eRegister.apply(walker);
  }

  NStmt_Jmpreg(int line, int pos, N$32 p$32, NRegister pRegister) {
    this.line = line;
    this.pos = pos;
    this.e$32 = p$32;
    this.eRegister = pRegister;
  }

  @Override
  public Type getType() {
    return Type.T_Stmt_Jmpreg;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmt;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmt_Jmpreg;
  }

  public NRegister get_Register() {
    return this.eRegister;
  }

  N$32 internalGet$32() {
    return this.e$32;
  }

  NRegister internalGetRegister() {
    return this.eRegister;
  }
}
