/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NStmt_Add
    extends NStmt {

  private final int line;
  private final int pos;
  private final N$0 e$0;
  private final NRegExpr eRegExpr;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inStmt_Add(this);
    walker.caseStmt_Add(this);
    walker.outStmt_Add(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$0.apply(walker);
    this.eRegExpr.apply(walker);
  }

  NStmt_Add(int line, int pos, N$0 p$0, NRegExpr pRegExpr) {
    this.line = line;
    this.pos = pos;
    this.e$0 = p$0;
    this.eRegExpr = pRegExpr;
  }

  @Override
  public Type getType() {
    return Type.T_Stmt_Add;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmt;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmt_Add;
  }

  public NRegExpr get_RegExpr() {
    return this.eRegExpr;
  }

  N$0 internalGet$0() {
    return this.e$0;
  }

  NRegExpr internalGetRegExpr() {
    return this.eRegExpr;
  }
}
