/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NStmt_Sb
    extends NStmt {

  private final int line;
  private final int pos;
  private final N$29 e$29;
  private final NArray eArray;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inStmt_Sb(this);
    walker.caseStmt_Sb(this);
    walker.outStmt_Sb(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$29.apply(walker);
    this.eArray.apply(walker);
  }

  NStmt_Sb(int line, int pos, N$29 p$29, NArray pArray) {
    this.line = line;
    this.pos = pos;
    this.e$29 = p$29;
    this.eArray = pArray;
  }

  @Override
  public Type getType() {
    return Type.T_Stmt_Sb;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmt;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmt_Sb;
  }

  public NArray get_Array() {
    return this.eArray;
  }

  N$29 internalGet$29() {
    return this.e$29;
  }

  NArray internalGetArray() {
    return this.eArray;
  }
}
