/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NStmt_Addiu
    extends NStmt {

  private final int line;
  private final int pos;
  private final N$3 e$3;
  private final NImmExpru eImmExpru;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inStmt_Addiu(this);
    walker.caseStmt_Addiu(this);
    walker.outStmt_Addiu(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$3.apply(walker);
    this.eImmExpru.apply(walker);
  }

  NStmt_Addiu(int line, int pos, N$3 p$3, NImmExpru pImmExpru) {
    this.line = line;
    this.pos = pos;
    this.e$3 = p$3;
    this.eImmExpru = pImmExpru;
  }

  @Override
  public Type getType() {
    return Type.T_Stmt_Addiu;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmt;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmt_Addiu;
  }

  public NImmExpru get_ImmExpru() {
    return this.eImmExpru;
  }

  N$3 internalGet$3() {
    return this.e$3;
  }

  NImmExpru internalGetImmExpru() {
    return this.eImmExpru;
  }
}
