/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NStmt_Ll
    extends NStmt {

  private final int line;
  private final int pos;
  private final N$23 e$23;
  private final NImmExpr eImmExpr;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inStmt_Ll(this);
    walker.caseStmt_Ll(this);
    walker.outStmt_Ll(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$23.apply(walker);
    this.eImmExpr.apply(walker);
  }

  NStmt_Ll(int line, int pos, N$23 p$23, NImmExpr pImmExpr) {
    this.line = line;
    this.pos = pos;
    this.e$23 = p$23;
    this.eImmExpr = pImmExpr;
  }

  @Override
  public Type getType() {
    return Type.T_Stmt_Ll;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmt;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmt_Ll;
  }

  public NImmExpr get_ImmExpr() {
    return this.eImmExpr;
  }

  N$23 internalGet$23() {
    return this.e$23;
  }

  NImmExpr internalGetImmExpr() {
    return this.eImmExpr;
  }
}
