/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NStmt_Lhu
    extends NStmt {

  private final int line;
  private final int pos;
  private final N$24 e$24;
  private final NArray eArray;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inStmt_Lhu(this);
    walker.caseStmt_Lhu(this);
    walker.outStmt_Lhu(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$24.apply(walker);
    this.eArray.apply(walker);
  }

  NStmt_Lhu(int line, int pos, N$24 p$24, NArray pArray) {
    this.line = line;
    this.pos = pos;
    this.e$24 = p$24;
    this.eArray = pArray;
  }

  @Override
  public Type getType() {
    return Type.T_Stmt_Lhu;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmt;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmt_Lhu;
  }

  public NArray get_Array() {
    return this.eArray;
  }

  N$24 internalGet$24() {
    return this.e$24;
  }

  NArray internalGetArray() {
    return this.eArray;
  }
}
