/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NStmt_Jmpreg
    extends NStmt {

  private final int line;
  private final int pos;
  private final N$35 e$35;
  private final NRs eRs;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inStmt_Jmpreg(this);
    walker.caseStmt_Jmpreg(this);
    walker.outStmt_Jmpreg(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$35.apply(walker);
    this.eRs.apply(walker);
  }

  NStmt_Jmpreg(int line, int pos, N$35 p$35, NRs pRs) {
    this.line = line;
    this.pos = pos;
    this.e$35 = p$35;
    this.eRs = pRs;
  }

  @Override
  public Type getType() {
    return Type.T_Stmt_Jmpreg;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmt;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmt_Jmpreg;
  }

  public NRs get_Rs() {
    return this.eRs;
  }

  N$35 internalGet$35() {
    return this.e$35;
  }

  NRs internalGetRs() {
    return this.eRs;
  }
}
