/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NStmt_Lhu
    extends NStmt {

  private final int line;
  private final int pos;
  private final N$22 e$22;
  private final NImmExpr eImmExpr;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inStmt_Lhu(this);
    walker.caseStmt_Lhu(this);
    walker.outStmt_Lhu(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$22.apply(walker);
    this.eImmExpr.apply(walker);
  }

  NStmt_Lhu(int line, int pos, N$22 p$22, NImmExpr pImmExpr) {
    this.line = line;
    this.pos = pos;
    this.e$22 = p$22;
    this.eImmExpr = pImmExpr;
  }

  @Override
  public Type getType() {
    return Type.T_Stmt_Lhu;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmt;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmt_Lhu;
  }

  public NImmExpr get_ImmExpr() {
    return this.eImmExpr;
  }

  N$22 internalGet$22() {
    return this.e$22;
  }

  NImmExpr internalGetImmExpr() {
    return this.eImmExpr;
  }
}
