/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NStmt_Sh
    extends NStmt {

  private final int line;
  private final int pos;
  private final N$28 e$28;
  private final NImmExpr eImmExpr;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inStmt_Sh(this);
    walker.caseStmt_Sh(this);
    walker.outStmt_Sh(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$28.apply(walker);
    this.eImmExpr.apply(walker);
  }

  NStmt_Sh(int line, int pos, N$28 p$28, NImmExpr pImmExpr) {
    this.line = line;
    this.pos = pos;
    this.e$28 = p$28;
    this.eImmExpr = pImmExpr;
  }

  @Override
  public Type getType() {
    return Type.T_Stmt_Sh;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmt;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmt_Sh;
  }

  public NImmExpr get_ImmExpr() {
    return this.eImmExpr;
  }

  N$28 internalGet$28() {
    return this.e$28;
  }

  NImmExpr internalGetImmExpr() {
    return this.eImmExpr;
  }
}
