/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NStmts_One
    extends NStmts {

  private final int line;
  private final int pos;
  private final NStmt eStmt;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inStmts_One(this);
    walker.caseStmts_One(this);
    walker.outStmts_One(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eStmt.apply(walker);
  }

  public NStmts_One(int line, int pos, NStmt pStmt) {
    this.line = line;
    this.pos = pos;
    this.eStmt = pStmt;
  }

  @Override
  public Type getType() {
    return Type.T_Stmts_One;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmts;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmts_One;
  }

  public NStmt get_Stmt() {
    return this.eStmt;
  }

  NStmt internalGetStmt() {
    return this.eStmt;
  }
}
