/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NStmt_Or
    extends NStmt {

  private final int line;
  private final int pos;
  private final N$8 e$8;
  private final NRegExpr eRegExpr;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inStmt_Or(this);
    walker.caseStmt_Or(this);
    walker.outStmt_Or(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$8.apply(walker);
    this.eRegExpr.apply(walker);
  }

  NStmt_Or(int line, int pos, N$8 p$8, NRegExpr pRegExpr) {
    this.line = line;
    this.pos = pos;
    this.e$8 = p$8;
    this.eRegExpr = pRegExpr;
  }

  @Override
  public Type getType() {
    return Type.T_Stmt_Or;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmt;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmt_Or;
  }

  public NRegExpr get_RegExpr() {
    return this.eRegExpr;
  }

  N$8 internalGet$8() {
    return this.e$8;
  }

  NRegExpr internalGetRegExpr() {
    return this.eRegExpr;
  }
}
