/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NStmt_Addi
    extends NStmt {

  private final int line;
  private final int pos;
  private final N$1 e$1;
  private final NImmExpr eImmExpr;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inStmt_Addi(this);
    walker.caseStmt_Addi(this);
    walker.outStmt_Addi(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$1.apply(walker);
    this.eImmExpr.apply(walker);
  }

  NStmt_Addi(int line, int pos, N$1 p$1, NImmExpr pImmExpr) {
    this.line = line;
    this.pos = pos;
    this.e$1 = p$1;
    this.eImmExpr = pImmExpr;
  }

  @Override
  public Type getType() {
    return Type.T_Stmt_Addi;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmt;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmt_Addi;
  }

  public NImmExpr get_ImmExpr() {
    return this.eImmExpr;
  }

  N$1 internalGet$1() {
    return this.e$1;
  }

  NImmExpr internalGetImmExpr() {
    return this.eImmExpr;
  }
}
