/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NStmt_Syscall
    extends NStmt {

  private final int line;
  private final int pos;
  private final N$40 e$40;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inStmt_Syscall(this);
    walker.caseStmt_Syscall(this);
    walker.outStmt_Syscall(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$40.apply(walker);
  }

  NStmt_Syscall(int line, int pos, N$40 p$40) {
    this.line = line;
    this.pos = pos;
    this.e$40 = p$40;
  }

  @Override
  public Type getType() {
    return Type.T_Stmt_Syscall;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmt;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmt_Syscall;
  }

  N$40 internalGet$40() {
    return this.e$40;
  }
}
