/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NStmt_Lbu
    extends NStmt {

  private final int line;
  private final int pos;
  private final N$21 e$21;
  private final NArray eArray;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inStmt_Lbu(this);
    walker.caseStmt_Lbu(this);
    walker.outStmt_Lbu(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$21.apply(walker);
    this.eArray.apply(walker);
  }

  NStmt_Lbu(int line, int pos, N$21 p$21, NArray pArray) {
    this.line = line;
    this.pos = pos;
    this.e$21 = p$21;
    this.eArray = pArray;
  }

  @Override
  public Type getType() {
    return Type.T_Stmt_Lbu;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmt;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmt_Lbu;
  }

  public NArray get_Array() {
    return this.eArray;
  }

  N$21 internalGet$21() {
    return this.e$21;
  }

  NArray internalGetArray() {
    return this.eArray;
  }
}
