/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NStmt_Jmplnk
    extends NStmt {

  private final int line;
  private final int pos;
  private final N$36 e$36;
  private final NString eString;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inStmt_Jmplnk(this);
    walker.caseStmt_Jmplnk(this);
    walker.outStmt_Jmplnk(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$36.apply(walker);
    this.eString.apply(walker);
  }

  NStmt_Jmplnk(int line, int pos, N$36 p$36, NString pString) {
    this.line = line;
    this.pos = pos;
    this.e$36 = p$36;
    this.eString = pString;
  }

  @Override
  public Type getType() {
    return Type.T_Stmt_Jmplnk;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmt;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmt_Jmplnk;
  }

  public NString get_String() {
    return this.eString;
  }

  N$36 internalGet$36() {
    return this.e$36;
  }

  NString internalGetString() {
    return this.eString;
  }
}
