/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NStmt_Sc
    extends NStmt {

  private final int line;
  private final int pos;
  private final N$30 e$30;
  private final NArray eArray;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inStmt_Sc(this);
    walker.caseStmt_Sc(this);
    walker.outStmt_Sc(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$30.apply(walker);
    this.eArray.apply(walker);
  }

  NStmt_Sc(int line, int pos, N$30 p$30, NArray pArray) {
    this.line = line;
    this.pos = pos;
    this.e$30 = p$30;
    this.eArray = pArray;
  }

  @Override
  public Type getType() {
    return Type.T_Stmt_Sc;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmt;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmt_Sc;
  }

  public NArray get_Array() {
    return this.eArray;
  }

  N$30 internalGet$30() {
    return this.e$30;
  }

  NArray internalGetArray() {
    return this.eArray;
  }
}
