/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NStmt_Sltu
    extends NStmt {

  private final int line;
  private final int pos;
  private final N$15 e$15;
  private final NImmExpr eImmExpr;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inStmt_Sltu(this);
    walker.caseStmt_Sltu(this);
    walker.outStmt_Sltu(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$15.apply(walker);
    this.eImmExpr.apply(walker);
  }

  NStmt_Sltu(int line, int pos, N$15 p$15, NImmExpr pImmExpr) {
    this.line = line;
    this.pos = pos;
    this.e$15 = p$15;
    this.eImmExpr = pImmExpr;
  }

  @Override
  public Type getType() {
    return Type.T_Stmt_Sltu;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmt;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmt_Sltu;
  }

  public NImmExpr get_ImmExpr() {
    return this.eImmExpr;
  }

  N$15 internalGet$15() {
    return this.e$15;
  }

  NImmExpr internalGetImmExpr() {
    return this.eImmExpr;
  }
}
