/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NStmt_Sh
    extends NStmt {

  private final int line;
  private final int pos;
  private final N$31 e$31;
  private final NArray eArray;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inStmt_Sh(this);
    walker.caseStmt_Sh(this);
    walker.outStmt_Sh(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$31.apply(walker);
    this.eArray.apply(walker);
  }

  NStmt_Sh(int line, int pos, N$31 p$31, NArray pArray) {
    this.line = line;
    this.pos = pos;
    this.e$31 = p$31;
    this.eArray = pArray;
  }

  @Override
  public Type getType() {
    return Type.T_Stmt_Sh;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmt;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmt_Sh;
  }

  public NArray get_Array() {
    return this.eArray;
  }

  N$31 internalGet$31() {
    return this.e$31;
  }

  NArray internalGetArray() {
    return this.eArray;
  }
}
