/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NStmt_Text
    extends NStmt {

  private final int line;
  private final int pos;
  private final N$38 e$38;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inStmt_Text(this);
    walker.caseStmt_Text(this);
    walker.outStmt_Text(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$38.apply(walker);
  }

  NStmt_Text(int line, int pos, N$38 p$38) {
    this.line = line;
    this.pos = pos;
    this.e$38 = p$38;
  }

  @Override
  public Type getType() {
    return Type.T_Stmt_Text;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmt;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmt_Text;
  }

  N$38 internalGet$38() {
    return this.e$38;
  }
}
