/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NStmt_Sw
    extends NStmt {

  private final int line;
  private final int pos;
  private final N$29 e$29;
  private final NImmExpr eImmExpr;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inStmt_Sw(this);
    walker.caseStmt_Sw(this);
    walker.outStmt_Sw(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$29.apply(walker);
    this.eImmExpr.apply(walker);
  }

  NStmt_Sw(int line, int pos, N$29 p$29, NImmExpr pImmExpr) {
    this.line = line;
    this.pos = pos;
    this.e$29 = p$29;
    this.eImmExpr = pImmExpr;
  }

  @Override
  public Type getType() {
    return Type.T_Stmt_Sw;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmt;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmt_Sw;
  }

  public NImmExpr get_ImmExpr() {
    return this.eImmExpr;
  }

  N$29 internalGet$29() {
    return this.e$29;
  }

  NImmExpr internalGetImmExpr() {
    return this.eImmExpr;
  }
}
