/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NStmt_Slt
    extends NStmt {

  private final int line;
  private final int pos;
  private final N$11 e$11;
  private final NRegExpr eRegExpr;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inStmt_Slt(this);
    walker.caseStmt_Slt(this);
    walker.outStmt_Slt(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$11.apply(walker);
    this.eRegExpr.apply(walker);
  }

  NStmt_Slt(int line, int pos, N$11 p$11, NRegExpr pRegExpr) {
    this.line = line;
    this.pos = pos;
    this.e$11 = p$11;
    this.eRegExpr = pRegExpr;
  }

  @Override
  public Type getType() {
    return Type.T_Stmt_Slt;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmt;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmt_Slt;
  }

  public NRegExpr get_RegExpr() {
    return this.eRegExpr;
  }

  N$11 internalGet$11() {
    return this.e$11;
  }

  NRegExpr internalGetRegExpr() {
    return this.eRegExpr;
  }
}
