/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NStmt_Lui
    extends NStmt {

  private final int line;
  private final int pos;
  private final N$25 e$25;
  private final NRt eRt;
  private final N$26 e$26;
  private final NImmediate eImmediate;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inStmt_Lui(this);
    walker.caseStmt_Lui(this);
    walker.outStmt_Lui(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$25.apply(walker);
    this.eRt.apply(walker);
    this.e$26.apply(walker);
    this.eImmediate.apply(walker);
  }

  NStmt_Lui(int line, int pos, N$25 p$25, NRt pRt, N$26 p$26, NImmediate pImmediate) {
    this.line = line;
    this.pos = pos;
    this.e$25 = p$25;
    this.eRt = pRt;
    this.e$26 = p$26;
    this.eImmediate = pImmediate;
  }

  @Override
  public Type getType() {
    return Type.T_Stmt_Lui;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmt;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmt_Lui;
  }

  public NRt get_Rt() {
    return this.eRt;
  }

  public NImmediate get_Immediate() {
    return this.eImmediate;
  }

  N$25 internalGet$25() {
    return this.e$25;
  }

  NRt internalGetRt() {
    return this.eRt;
  }

  N$26 internalGet$26() {
    return this.e$26;
  }

  NImmediate internalGetImmediate() {
    return this.eImmediate;
  }
}
