/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NStmt_Jmllnk
    extends NStmt {

  private final int line;
  private final int pos;
  private final N$33 e$33;
  private final NString eString;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inStmt_Jmllnk(this);
    walker.caseStmt_Jmllnk(this);
    walker.outStmt_Jmllnk(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$33.apply(walker);
    this.eString.apply(walker);
  }

  NStmt_Jmllnk(int line, int pos, N$33 p$33, NString pString) {
    this.line = line;
    this.pos = pos;
    this.e$33 = p$33;
    this.eString = pString;
  }

  @Override
  public Type getType() {
    return Type.T_Stmt_Jmllnk;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmt;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmt_Jmllnk;
  }

  public NString get_String() {
    return this.eString;
  }

  N$33 internalGet$33() {
    return this.e$33;
  }

  NString internalGetString() {
    return this.eString;
  }
}
