/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NStmt_And
    extends NStmt {

  private final int line;
  private final int pos;
  private final N$6 e$6;
  private final NRegExpr eRegExpr;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inStmt_And(this);
    walker.caseStmt_And(this);
    walker.outStmt_And(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$6.apply(walker);
    this.eRegExpr.apply(walker);
  }

  NStmt_And(int line, int pos, N$6 p$6, NRegExpr pRegExpr) {
    this.line = line;
    this.pos = pos;
    this.e$6 = p$6;
    this.eRegExpr = pRegExpr;
  }

  @Override
  public Type getType() {
    return Type.T_Stmt_And;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmt;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmt_And;
  }

  public NRegExpr get_RegExpr() {
    return this.eRegExpr;
  }

  N$6 internalGet$6() {
    return this.e$6;
  }

  NRegExpr internalGetRegExpr() {
    return this.eRegExpr;
  }
}
