/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NStmt_Mov
    extends NStmt {

  private final int line;
  private final int pos;
  private final N$41 e$41;
  private final NRegister eRegister$1;
  private final N$20 e$20;
  private final NRegister eRegister$2;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inStmt_Mov(this);
    walker.caseStmt_Mov(this);
    walker.outStmt_Mov(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$41.apply(walker);
    this.eRegister$1.apply(walker);
    this.e$20.apply(walker);
    this.eRegister$2.apply(walker);
  }

  NStmt_Mov(int line, int pos, N$41 p$41, NRegister pRegister$1, N$20 p$20, NRegister pRegister$2) {
    this.line = line;
    this.pos = pos;
    this.e$41 = p$41;
    this.eRegister$1 = pRegister$1;
    this.e$20 = p$20;
    this.eRegister$2 = pRegister$2;
  }

  @Override
  public Type getType() {
    return Type.T_Stmt_Mov;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmt;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmt_Mov;
  }

  N$41 internalGet$41() {
    return this.e$41;
  }

  NRegister internalGetRegister$1() {
    return this.eRegister$1;
  }

  N$20 internalGet$20() {
    return this.e$20;
  }

  NRegister internalGetRegister$2() {
    return this.eRegister$2;
  }
}
