/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NStmt_Nor
    extends NStmt {

  private final int line;
  private final int pos;
  private final N$10 e$10;
  private final NRegExpr eRegExpr;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inStmt_Nor(this);
    walker.caseStmt_Nor(this);
    walker.outStmt_Nor(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$10.apply(walker);
    this.eRegExpr.apply(walker);
  }

  NStmt_Nor(int line, int pos, N$10 p$10, NRegExpr pRegExpr) {
    this.line = line;
    this.pos = pos;
    this.e$10 = p$10;
    this.eRegExpr = pRegExpr;
  }

  @Override
  public Type getType() {
    return Type.T_Stmt_Nor;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmt;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmt_Nor;
  }

  public NRegExpr get_RegExpr() {
    return this.eRegExpr;
  }

  N$10 internalGet$10() {
    return this.e$10;
  }

  NRegExpr internalGetRegExpr() {
    return this.eRegExpr;
  }
}
