/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NStmt_Lui
    extends NStmt {

  private final int line;
  private final int pos;
  private final N$26 e$26;
  private final NRt eRt;
  private final N$20 e$20;
  private final NNumber eNumber;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inStmt_Lui(this);
    walker.caseStmt_Lui(this);
    walker.outStmt_Lui(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$26.apply(walker);
    this.eRt.apply(walker);
    this.e$20.apply(walker);
    this.eNumber.apply(walker);
  }

  NStmt_Lui(int line, int pos, N$26 p$26, NRt pRt, N$20 p$20, NNumber pNumber) {
    this.line = line;
    this.pos = pos;
    this.e$26 = p$26;
    this.eRt = pRt;
    this.e$20 = p$20;
    this.eNumber = pNumber;
  }

  @Override
  public Type getType() {
    return Type.T_Stmt_Lui;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmt;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmt_Lui;
  }

  public NRt get_Rt() {
    return this.eRt;
  }

  public NNumber get_Number() {
    return this.eNumber;
  }

  N$26 internalGet$26() {
    return this.e$26;
  }

  NRt internalGetRt() {
    return this.eRt;
  }

  N$20 internalGet$20() {
    return this.e$20;
  }

  NNumber internalGetNumber() {
    return this.eNumber;
  }
}
