/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class NStmt_Li
    extends NStmt {

  private final int line;
  private final int pos;
  private final N$43 e$43;
  private final NRegister eRegister;
  private final N$20 e$20;
  private final NNumber eNumber;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inStmt_Li(this);
    walker.caseStmt_Li(this);
    walker.outStmt_Li(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$43.apply(walker);
    this.eRegister.apply(walker);
    this.e$20.apply(walker);
    this.eNumber.apply(walker);
  }

  NStmt_Li(int line, int pos, N$43 p$43, NRegister pRegister, N$20 p$20, NNumber pNumber) {
    this.line = line;
    this.pos = pos;
    this.e$43 = p$43;
    this.eRegister = pRegister;
    this.e$20 = p$20;
    this.eNumber = pNumber;
  }

  @Override
  public Type getType() {
    return Type.T_Stmt_Li;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Stmt;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Stmt_Li;
  }

  public NRegister get_Register() {
    return this.eRegister;
  }

  public NNumber get_Number() {
    return this.eNumber;
  }

  N$43 internalGet$43() {
    return this.e$43;
  }

  NRegister internalGetRegister() {
    return this.eRegister;
  }

  N$20 internalGet$20() {
    return this.e$20;
  }

  NNumber internalGetNumber() {
    return this.eNumber;
  }
}
