/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_0
    extends TransitionState {

  static final S_0 instance = new S_0();

  private S_0() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol_9:
      return S_1.instance;
    case Symbol_10:
      return S_1.instance;
    case Symbol_13:
      return S_1.instance;
    case Symbol_34:
      return S_2.instance;
    case Symbol_35:
      return S_3.instance;
    case Symbol_36:
      return S_4.instance;
    case Symbol_40:
      return S_5.instance;
    case Symbol_41:
      return S_6.instance;
    case Symbol_44:
      return S_7.instance;
    case Symbol_45:
      return S_8.instance;
    case Symbol_46:
      return S_9.instance;
    case Symbol__0:
      return S_10.instance;
    case Symbol__1:
      return S_11.instance;
    case Symbol__2:
      return S_11.instance;
    case Symbol__3:
      return S_11.instance;
    case Symbol__4:
      return S_11.instance;
    case Symbol__8:
      return S_11.instance;
    case Symbol_58:
      return S_12.instance;
    case Symbol_59:
      return S_13.instance;
    case Symbol__A:
      return S_14.instance;
    case Symbol_95:
      return S_15.instance;
    case Symbol__a:
      return S_16.instance;
    case Symbol__b:
      return S_17.instance;
    case Symbol__c:
      return S_14.instance;
    case Symbol__d:
      return S_14.instance;
    case Symbol__e:
      return S_14.instance;
    case Symbol__f:
      return S_14.instance;
    case Symbol__g:
      return S_14.instance;
    case Symbol__h:
      return S_14.instance;
    case Symbol__i:
      return S_14.instance;
    case Symbol__j:
      return S_18.instance;
    case Symbol__k:
      return S_14.instance;
    case Symbol__l:
      return S_19.instance;
    case Symbol__m:
      return S_20.instance;
    case Symbol__n:
      return S_21.instance;
    case Symbol__o:
      return S_22.instance;
    case Symbol__p:
      return S_14.instance;
    case Symbol__q:
      return S_14.instance;
    case Symbol__r:
      return S_14.instance;
    case Symbol__s:
      return S_23.instance;
    case Symbol__t:
      return S_14.instance;
    case Symbol__u:
      return S_14.instance;
    case Symbol__v:
      return S_14.instance;
    case Symbol__w:
      return S_14.instance;
    case Symbol__x:
      return S_24.instance;
    case Symbol__y:
      return S_14.instance;
    case Symbol__z:
      return S_14.instance;
    default:
      return null;
    }
  }

}
