/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_109
    extends FinalState {

  static final S_109 instance = new S_109();

  private S_109() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(2);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$22(text, line, pos);
  }
}
