/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_104
    extends FinalState {

  static final S_104 instance = new S_104();

  private S_104() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$21(text, line, pos);
  }
}
