/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_108
    extends FinalState {

  static final S_108 instance = new S_108();

  private S_108() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$5(text, line, pos);
  }
}
