/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_102
    extends FinalState {

  static final S_102 instance = new S_102();

  private S_102() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$19(text, line, pos);
  }
}
