/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_101
    extends FinalState {

  static final S_101 instance = new S_101();

  private S_101() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(2);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$5(text, line, pos);
  }
}
