/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_114
    extends FinalState {

  static final S_114 instance = new S_114();

  private S_114() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$9(text, line, pos);
  }
}
