/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_118
    extends TransitionState {

  static final S_118 instance = new S_118();

  private S_118() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__o:
      return S_75.instance;
    default:
      return null;
    }
  }

}
