/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_112
    extends FinalState {

  static final S_112 instance = new S_112();

  private S_112() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(2);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$27(text, line, pos);
  }
}
