/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_117
    extends FinalState {

  static final S_117 instance = new S_117();

  private S_117() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(2);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$27(text, line, pos);
  }
}
