/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_118
    extends FinalState {

  static final S_118 instance = new S_118();

  private S_118() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(2);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$28(text, line, pos);
  }
}
