/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_119
    extends FinalState {

  static final S_119 instance = new S_119();

  private S_119() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$10(text, line, pos);
  }
}
