/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_115
    extends FinalState {

  static final S_115 instance = new S_115();

  private S_115() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(2);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$25(text, line, pos);
  }
}
