/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_113
    extends FinalState {

  static final S_113 instance = new S_113();

  private S_113() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$24(text, line, pos);
  }
}
