/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_119
    extends TransitionState {

  static final S_119 instance = new S_119();

  private S_119() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__g:
      return S_154.instance;
    default:
      return null;
    }
  }

}
