/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_122
    extends FinalState {

  static final S_122 instance = new S_122();

  private S_122() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$9(text, line, pos);
  }
}
