/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_121
    extends TransitionState {

  static final S_121 instance = new S_121();

  private S_121() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__e:
      return S_156.instance;
    default:
      return null;
    }
  }

}
