/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_12
    extends FinalState {

  static final S_12 instance = new S_12();

  private S_12() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(0);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$33(text, line, pos);
  }
}
