/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_123
    extends TransitionState {

  static final S_123 instance = new S_123();

  private S_123() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__b:
      return S_158.instance;
    default:
      return null;
    }
  }

}
