/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_129
    extends TransitionState {

  static final S_129 instance = new S_129();

  private S_129() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__d:
      return S_164.instance;
    default:
      return null;
    }
  }

}
