/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_127
    extends FinalState {

  static final S_127 instance = new S_127();

  private S_127() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$17(text, line, pos);
  }
}
