/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_124
    extends FinalState {

  static final S_124 instance = new S_124();

  private S_124() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(2);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$29(text, line, pos);
  }
}
