/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_120
    extends TransitionState {

  static final S_120 instance = new S_120();

  private S_120() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__i:
      return S_155.instance;
    default:
      return null;
    }
  }

}
