/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_127
    extends TransitionState {

  static final S_127 instance = new S_127();

  private S_127() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__c:
      return S_162.instance;
    default:
      return null;
    }
  }

}
