/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_124
    extends TransitionState {

  static final S_124 instance = new S_124();

  private S_124() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__a:
      return S_159.instance;
    default:
      return null;
    }
  }

}
