/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_126
    extends TransitionState {

  static final S_126 instance = new S_126();

  private S_126() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__f:
      return S_161.instance;
    default:
      return null;
    }
  }

}
