/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_125
    extends TransitionState {

  static final S_125 instance = new S_125();

  private S_125() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__b:
      return S_160.instance;
    default:
      return null;
    }
  }

}
