/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_128
    extends TransitionState {

  static final S_128 instance = new S_128();

  private S_128() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__t:
      return S_163.instance;
    default:
      return null;
    }
  }

}
