/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_138
    extends FinalState {

  static final S_138 instance = new S_138();

  private S_138() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$22(text, line, pos);
  }
}
