/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_134
    extends FinalState {

  static final S_134 instance = new S_134();

  private S_134() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(2);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$0(text, line, pos);
  }
}
