/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_135
    extends FinalState {

  static final S_135 instance = new S_135();

  private S_135() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$1(text, line, pos);
  }
}
