/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_137
    extends FinalState {

  static final S_137 instance = new S_137();

  private S_137() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$36(text, line, pos);
  }
}
