/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_13
    extends FinalState {

  static final S_13 instance = new S_13();

  private S_13() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(0);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$55(text, line, pos);
  }
}
