/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_136
    extends FinalState {

  static final S_136 instance = new S_136();

  private S_136() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$21(text, line, pos);
  }
}
