/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_133
    extends FinalState {

  static final S_133 instance = new S_133();

  private S_133() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$6(text, line, pos);
  }
}
