/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_130
    extends FinalState {

  static final S_130 instance = new S_130();

  private S_130() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(2);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$29(text, line, pos);
  }
}
