/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_131
    extends FinalState {

  static final S_131 instance = new S_131();

  private S_131() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$11(text, line, pos);
  }
}
