/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_146
    extends FinalState {

  static final S_146 instance = new S_146();

  private S_146() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$2(text, line, pos);
  }
}
