/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_142
    extends TransitionState {

  static final S_142 instance = new S_142();

  private S_142() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol_min:
      return S_169.instance;
    case Symbol_9:
      return S_169.instance;
    case Symbol_36:
      return S_169.instance;
    case Symbol_44:
      return S_169.instance;
    case Symbol_45:
      return S_169.instance;
    case Symbol__0:
      return S_7.instance;
    case Symbol__1:
      return S_7.instance;
    case Symbol__2:
      return S_7.instance;
    case Symbol__3:
      return S_7.instance;
    case Symbol__4:
      return S_7.instance;
    case Symbol__8:
      return S_7.instance;
    case Symbol_58:
      return S_169.instance;
    case Symbol__A:
      return S_169.instance;
    case Symbol_95:
      return S_169.instance;
    case Symbol__a:
      return S_169.instance;
    case Symbol__b:
      return S_169.instance;
    case Symbol__c:
      return S_169.instance;
    case Symbol__d:
      return S_169.instance;
    case Symbol__e:
      return S_169.instance;
    case Symbol__f:
      return S_169.instance;
    case Symbol__h:
      return S_169.instance;
    case Symbol__i:
      return S_169.instance;
    case Symbol__j:
      return S_169.instance;
    case Symbol__k:
      return S_169.instance;
    case Symbol__l:
      return S_169.instance;
    case Symbol__n:
      return S_169.instance;
    case Symbol__o:
      return S_169.instance;
    case Symbol__p:
      return S_169.instance;
    case Symbol__q:
      return S_169.instance;
    case Symbol__r:
      return S_169.instance;
    case Symbol__s:
      return S_169.instance;
    case Symbol__t:
      return S_169.instance;
    case Symbol__u:
      return S_169.instance;
    case Symbol__v:
      return S_169.instance;
    case Symbol__w:
      return S_169.instance;
    case Symbol__x:
      return S_169.instance;
    case Symbol__z:
      return S_169.instance;
    case Symbol_end:
      return S_169.instance;
    default:
      return null;
    }
  }

}
