/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_140
    extends FinalState {

  static final S_140 instance = new S_140();

  private S_140() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(2);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$6(text, line, pos);
  }
}
