/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_143
    extends FinalState {

  static final S_143 instance = new S_143();

  private S_143() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$9(text, line, pos);
  }
}
