/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_141
    extends FinalState {

  static final S_141 instance = new S_141();

  private S_141() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$41(text, line, pos);
  }
}
