/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_147
    extends FinalState {

  static final S_147 instance = new S_147();

  private S_147() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(2);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$22(text, line, pos);
  }
}
