/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_149
    extends FinalState {

  static final S_149 instance = new S_149();

  private S_149() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(2);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$10(text, line, pos);
  }
}
