/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_144
    extends FinalState {

  static final S_144 instance = new S_144();

  private S_144() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(2);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$20(text, line, pos);
  }
}
