/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_155
    extends FinalState {

  static final S_155 instance = new S_155();

  private S_155() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(2);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$24(text, line, pos);
  }
}
