/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_155
    extends TransitionState {

  static final S_155 instance = new S_155();

  private S_155() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__i:
      return S_176.instance;
    default:
      return null;
    }
  }

}
