/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_153
    extends FinalState {

  static final S_153 instance = new S_153();

  private S_153() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$14(text, line, pos);
  }
}
