/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_158
    extends TransitionState {

  static final S_158 instance = new S_158();

  private S_158() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__l:
      return S_177.instance;
    default:
      return null;
    }
  }

}
