/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_151
    extends FinalState {

  static final S_151 instance = new S_151();

  private S_151() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(2);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$19(text, line, pos);
  }
}
