/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_152
    extends FinalState {

  static final S_152 instance = new S_152();

  private S_152() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$11(text, line, pos);
  }
}
