/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_15
    extends TransitionState {

  static final S_15 instance = new S_15();

  private S_15() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__0:
      return S_32.instance;
    case Symbol__1:
      return S_32.instance;
    default:
      return null;
    }
  }

}
