/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_159
    extends TransitionState {

  static final S_159 instance = new S_159();

  private S_159() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__t:
      return S_178.instance;
    default:
      return null;
    }
  }

}
