/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_157
    extends FinalState {

  static final S_157 instance = new S_157();

  private S_157() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(2);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$10(text, line, pos);
  }
}
