/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_159
    extends FinalState {

  static final S_159 instance = new S_159();

  private S_159() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(2);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$17(text, line, pos);
  }
}
