/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_150
    extends FinalState {

  static final S_150 instance = new S_150();

  private S_150() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(2);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$9(text, line, pos);
  }
}
