/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_154
    extends FinalState {

  static final S_154 instance = new S_154();

  private S_154() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(2);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$21(text, line, pos);
  }
}
