/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_154
    extends TransitionState {

  static final S_154 instance = new S_154();

  private S_154() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__n:
      return S_175.instance;
    default:
      return null;
    }
  }

}
