/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_162
    extends TransitionState {

  static final S_162 instance = new S_162();

  private S_162() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__e:
      return S_180.instance;
    default:
      return null;
    }
  }

}
