/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_162
    extends FinalState {

  static final S_162 instance = new S_162();

  private S_162() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(2);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$11(text, line, pos);
  }
}
