/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_161
    extends FinalState {

  static final S_161 instance = new S_161();

  private S_161() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(0);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$47(text, line, pos);
  }
}
