/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_160
    extends FinalState {

  static final S_160 instance = new S_160();

  private S_160() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$5(text, line, pos);
  }
}
