/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_16
    extends TransitionState {

  static final S_16 instance = new S_16();

  private S_16() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__a:
      return S_32.instance;
    default:
      return null;
    }
  }

}
