/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_167
    extends FinalState {

  static final S_167 instance = new S_167();

  private S_167() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$2(text, line, pos);
  }
}
