/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_160
    extends TransitionState {

  static final S_160 instance = new S_160();

  private S_160() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__l:
      return S_179.instance;
    default:
      return null;
    }
  }

}
