/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_165
    extends FinalState {

  static final S_165 instance = new S_165();

  private S_165() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$1(text, line, pos);
  }
}
