/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_164
    extends FinalState {

  static final S_164 instance = new S_164();

  private S_164() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(0);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$46(text, line, pos);
  }
}
