/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_169
    extends FinalState {

  static final S_169 instance = new S_169();

  private S_169() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$14(text, line, pos);
  }
}
