/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_168
    extends FinalState {

  static final S_168 instance = new S_168();

  private S_168() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$7(text, line, pos);
  }
}
