/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_176
    extends FinalState {

  static final S_176 instance = new S_176();

  private S_176() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(2);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$2(text, line, pos);
  }
}
