/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_179
    extends FinalState {

  static final S_179 instance = new S_179();

  private S_179() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(0);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$39(text, line, pos);
  }
}
