/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_177
    extends TransitionState {

  static final S_177 instance = new S_177();

  private S_177() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__e:
      return S_186.instance;
    default:
      return null;
    }
  }

}
