/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_175
    extends FinalState {

  static final S_175 instance = new S_175();

  private S_175() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(2);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$12(text, line, pos);
  }
}
