/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_17
    extends TransitionState {

  static final S_17 instance = new S_17();

  private S_17() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__0:
      return S_52.instance;
    case Symbol__1:
      return S_52.instance;
    case Symbol__2:
      return S_52.instance;
    case Symbol__3:
      return S_52.instance;
    case Symbol__t:
      return S_52.instance;
    default:
      return null;
    }
  }

}
