/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_183
    extends FinalState {

  static final S_183 instance = new S_183();

  private S_183() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(2);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$12(text, line, pos);
  }
}
