/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_184
    extends FinalState {

  static final S_184 instance = new S_184();

  private S_184() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(2);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$3(text, line, pos);
  }
}
