/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_188
    extends FinalState {

  static final S_188 instance = new S_188();

  private S_188() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$40(text, line, pos);
  }
}
