/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_180
    extends FinalState {

  static final S_180 instance = new S_180();

  private S_180() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(0);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$53(text, line, pos);
  }
}
