/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_182
    extends FinalState {

  static final S_182 instance = new S_182();

  private S_182() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$16(text, line, pos);
  }
}
