/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_18
    extends TransitionState {

  static final S_18 instance = new S_18();

  private S_18() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__p:
      return S_52.instance;
    default:
      return null;
    }
  }

}
