/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_2
    extends TransitionState {

  static final S_2 instance = new S_2();

  private S_2() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__a:
      return S_13.instance;
    case Symbol__f:
      return S_14.instance;
    case Symbol__k:
      return S_15.instance;
    case Symbol__r:
      return S_16.instance;
    case Symbol__s:
      return S_17.instance;
    case Symbol__t:
      return S_18.instance;
    case Symbol__v:
      return S_19.instance;
    case Symbol__z:
      return S_20.instance;
    default:
      return null;
    }
  }

}
