/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_20
    extends TransitionState {

  static final S_20 instance = new S_20();

  private S_20() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__e:
      return S_33.instance;
    default:
      return null;
    }
  }

}
