/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_21
    extends TransitionState {

  static final S_21 instance = new S_21();

  private S_21() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__0:
      return S_52.instance;
    case Symbol__1:
      return S_52.instance;
    case Symbol__2:
      return S_52.instance;
    case Symbol__3:
      return S_52.instance;
    case Symbol__4:
      return S_52.instance;
    case Symbol__p:
      return S_52.instance;
    default:
      return null;
    }
  }

}
