/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_22
    extends TransitionState {

  static final S_22 instance = new S_22();

  private S_22() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__0:
      return S_52.instance;
    case Symbol__1:
      return S_52.instance;
    case Symbol__2:
      return S_52.instance;
    case Symbol__3:
      return S_52.instance;
    case Symbol__4:
      return S_52.instance;
    case Symbol__8:
      return S_52.instance;
    default:
      return null;
    }
  }

}
