/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_22
    extends TransitionState {

  static final S_22 instance = new S_22();

  private S_22() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__a:
      return S_51.instance;
    default:
      return null;
    }
  }

}
