/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_22
    extends FinalState {

  static final S_22 instance = new S_22();

  private S_22() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new NNumberu(text, line, pos);
  }
}
