/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_23
    extends TransitionState {

  static final S_23 instance = new S_23();

  private S_23() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__0:
      return S_51.instance;
    case Symbol__1:
      return S_51.instance;
    case Symbol__2:
      return S_51.instance;
    case Symbol__3:
      return S_51.instance;
    case Symbol__4:
      return S_51.instance;
    case Symbol__p:
      return S_51.instance;
    default:
      return null;
    }
  }

}
