/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_23
    extends TransitionState {

  static final S_23 instance = new S_23();

  private S_23() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__0:
      return S_52.instance;
    case Symbol__3:
      return S_52.instance;
    default:
      return null;
    }
  }

}
