/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_23
    extends FinalState {

  static final S_23 instance = new S_23();

  private S_23() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new NString(text, line, pos);
  }
}
