/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_24
    extends TransitionState {

  static final S_24 instance = new S_24();

  private S_24() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__0:
      return S_51.instance;
    case Symbol__1:
      return S_51.instance;
    case Symbol__2:
      return S_51.instance;
    case Symbol__3:
      return S_51.instance;
    case Symbol__4:
      return S_51.instance;
    case Symbol__8:
      return S_51.instance;
    default:
      return null;
    }
  }

}
