/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_24
    extends TransitionState {

  static final S_24 instance = new S_24();

  private S_24() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__e:
      return S_53.instance;
    default:
      return null;
    }
  }

}
