/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_26
    extends TransitionState {

  static final S_26 instance = new S_26();

  private S_26() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__e:
      return S_55.instance;
    default:
      return null;
    }
  }

}
