/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_27
    extends FinalState {

  static final S_27 instance = new S_27();

  private S_27() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(0);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return null;
  }
}
