/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_28
    extends FinalState {

  static final S_28 instance = new S_28();

  private S_28() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return null;
  }
}
