/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_29
    extends TransitionState {

  static final S_29 instance = new S_29();

  private S_29() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__0:
      return S_75.instance;
    case Symbol__1:
      return S_75.instance;
    case Symbol__2:
      return S_75.instance;
    case Symbol__3:
      return S_75.instance;
    case Symbol__t:
      return S_75.instance;
    default:
      return null;
    }
  }

}
