/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_30
    extends TransitionState {

  static final S_30 instance = new S_30();

  private S_30() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__p:
      return S_75.instance;
    default:
      return null;
    }
  }

}
