/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_31
    extends TransitionState {

  static final S_31 instance = new S_31();

  private S_31() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__0:
      return S_75.instance;
    case Symbol__1:
      return S_75.instance;
    default:
      return null;
    }
  }

}
