/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_32
    extends TransitionState {

  static final S_32 instance = new S_32();

  private S_32() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__a:
      return S_75.instance;
    default:
      return null;
    }
  }

}
