/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_34
    extends TransitionState {

  static final S_34 instance = new S_34();

  private S_34() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__0:
      return S_75.instance;
    case Symbol__1:
      return S_75.instance;
    case Symbol__2:
      return S_75.instance;
    case Symbol__3:
      return S_75.instance;
    case Symbol__4:
      return S_75.instance;
    case Symbol__8:
      return S_75.instance;
    default:
      return null;
    }
  }

}
