/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_35
    extends FinalState {

  static final S_35 instance = new S_35();

  private S_35() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$34(text, line, pos);
  }
}
