/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_35
    extends TransitionState {

  static final S_35 instance = new S_35();

  private S_35() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__0:
      return S_75.instance;
    case Symbol__3:
      return S_75.instance;
    default:
      return null;
    }
  }

}
