/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_36
    extends TransitionState {

  static final S_36 instance = new S_36();

  private S_36() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__e:
      return S_76.instance;
    default:
      return null;
    }
  }

}
