/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_37
    extends TransitionState {

  static final S_37 instance = new S_37();

  private S_37() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__l:
      return S_77.instance;
    case Symbol__s:
      return S_78.instance;
    default:
      return null;
    }
  }

}
