/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_38
    extends TransitionState {

  static final S_38 instance = new S_38();

  private S_38() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__y:
      return S_79.instance;
    default:
      return null;
    }
  }

}
