/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_39
    extends TransitionState {

  static final S_39 instance = new S_39();

  private S_39() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__a:
      return S_80.instance;
    case Symbol__o:
      return S_81.instance;
    default:
      return null;
    }
  }

}
