/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_4
    extends TransitionState {

  static final S_4 instance = new S_4();

  private S_4() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__a:
      return S_29.instance;
    case Symbol__f:
      return S_30.instance;
    case Symbol__g:
      return S_30.instance;
    case Symbol__k:
      return S_31.instance;
    case Symbol__r:
      return S_32.instance;
    case Symbol__s:
      return S_33.instance;
    case Symbol__t:
      return S_34.instance;
    case Symbol__v:
      return S_35.instance;
    case Symbol__z:
      return S_36.instance;
    default:
      return null;
    }
  }

}
