/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_40
    extends TransitionState {

  static final S_40 instance = new S_40();

  private S_40() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__l:
      return S_82.instance;
    default:
      return null;
    }
  }

}
