/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_41
    extends TransitionState {

  static final S_41 instance = new S_41();

  private S_41() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__l:
      return S_83.instance;
    default:
      return null;
    }
  }

}
