/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_43
    extends TransitionState {

  static final S_43 instance = new S_43();

  private S_43() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__p:
      return S_85.instance;
    default:
      return null;
    }
  }

}
