/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_44
    extends TransitionState {

  static final S_44 instance = new S_44();

  private S_44() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__e:
      return S_86.instance;
    default:
      return null;
    }
  }

}
