/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_45
    extends TransitionState {

  static final S_45 instance = new S_45();

  private S_45() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__o:
      return S_87.instance;
    default:
      return null;
    }
  }

}
