/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_46
    extends TransitionState {

  static final S_46 instance = new S_46();

  private S_46() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__o:
      return S_32.instance;
    default:
      return null;
    }
  }

}
