/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_46
    extends FinalState {

  static final S_46 instance = new S_46();

  private S_46() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new NNumber(text, line, pos);
  }
}
