/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_47
    extends FinalState {

  static final S_47 instance = new S_47();

  private S_47() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$0(text, line, pos);
  }
}
