/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_5
    extends TransitionState {

  static final S_5 instance = new S_5();

  private S_5() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol_min:
      return S_22.instance;
    case Symbol_9:
      return S_22.instance;
    case Symbol_36:
      return S_22.instance;
    case Symbol_44:
      return S_22.instance;
    case Symbol_45:
      return S_22.instance;
    case Symbol__0:
      return S_5.instance;
    case Symbol__1:
      return S_5.instance;
    case Symbol__2:
      return S_5.instance;
    case Symbol__3:
      return S_5.instance;
    case Symbol__4:
      return S_5.instance;
    case Symbol__8:
      return S_5.instance;
    case Symbol_58:
      return S_22.instance;
    case Symbol__A:
      return S_22.instance;
    case Symbol_95:
      return S_22.instance;
    case Symbol__a:
      return S_22.instance;
    case Symbol__b:
      return S_22.instance;
    case Symbol__d:
      return S_22.instance;
    case Symbol__e:
      return S_22.instance;
    case Symbol__f:
      return S_22.instance;
    case Symbol__i:
      return S_22.instance;
    case Symbol__k:
      return S_22.instance;
    case Symbol__l:
      return S_22.instance;
    case Symbol__n:
      return S_22.instance;
    case Symbol__o:
      return S_22.instance;
    case Symbol__p:
      return S_22.instance;
    case Symbol__r:
      return S_22.instance;
    case Symbol__s:
      return S_22.instance;
    case Symbol__t:
      return S_22.instance;
    case Symbol__u:
      return S_22.instance;
    case Symbol__v:
      return S_22.instance;
    case Symbol__z:
      return S_22.instance;
    case Symbol_end:
      return S_22.instance;
    default:
      return null;
    }
  }

}
