/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_51
    extends FinalState {

  static final S_51 instance = new S_51();

  private S_51() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(0);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new NRegister(text, line, pos);
  }
}
