/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_52
    extends FinalState {

  static final S_52 instance = new S_52();

  private S_52() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(0);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new NRegister(text, line, pos);
  }
}
