/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_52
    extends TransitionState {

  static final S_52 instance = new S_52();

  private S_52() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__r:
      return S_78.instance;
    default:
      return null;
    }
  }

}
