/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_53
    extends TransitionState {

  static final S_53 instance = new S_53();

  private S_53() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__r:
      return S_88.instance;
    default:
      return null;
    }
  }

}
