/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_53
    extends FinalState {

  static final S_53 instance = new S_53();

  private S_53() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$34(text, line, pos);
  }
}
