/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_54
    extends FinalState {

  static final S_54 instance = new S_54();

  private S_54() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(0);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new NRegister(text, line, pos);
  }
}
