/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_55
    extends FinalState {

  static final S_55 instance = new S_55();

  private S_55() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(2);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new NString(text, line, pos);
  }
}
