/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_55
    extends TransitionState {

  static final S_55 instance = new S_55();

  private S_55() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__r:
      return S_94.instance;
    default:
      return null;
    }
  }

}
