/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_56
    extends FinalState {

  static final S_56 instance = new S_56();

  private S_56() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new NNumber(text, line, pos);
  }
}
