/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_60
    extends FinalState {

  static final S_60 instance = new S_60();

  private S_60() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(2);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$31(text, line, pos);
  }
}
