/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_63
    extends FinalState {

  static final S_63 instance = new S_63();

  private S_63() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$25(text, line, pos);
  }
}
