/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_66
    extends FinalState {

  static final S_66 instance = new S_66();

  private S_66() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$23(text, line, pos);
  }
}
