/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_67
    extends FinalState {

  static final S_67 instance = new S_67();

  private S_67() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$4(text, line, pos);
  }
}
