/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_69
    extends FinalState {

  static final S_69 instance = new S_69();

  private S_69() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$25(text, line, pos);
  }
}
