/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_7
    extends FinalState {

  static final S_7 instance = new S_7();

  private S_7() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(0);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$20(text, line, pos);
  }
}
