/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_70
    extends FinalState {

  static final S_70 instance = new S_70();

  private S_70() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$30(text, line, pos);
  }
}
