/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_71
    extends FinalState {

  static final S_71 instance = new S_71();

  private S_71() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$31(text, line, pos);
  }
}
