/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_72
    extends FinalState {

  static final S_72 instance = new S_72();

  private S_72() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$24(text, line, pos);
  }
}
