/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_74
    extends FinalState {

  static final S_74 instance = new S_74();

  private S_74() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$2(text, line, pos);
  }
}
