/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_76
    extends FinalState {

  static final S_76 instance = new S_76();

  private S_76() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$32(text, line, pos);
  }
}
