/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_76
    extends TransitionState {

  static final S_76 instance = new S_76();

  private S_76() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__r:
      return S_118.instance;
    default:
      return null;
    }
  }

}
