/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_77
    extends TransitionState {

  static final S_77 instance = new S_77();

  private S_77() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__i:
      return S_119.instance;
    default:
      return null;
    }
  }

}
