/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_77
    extends FinalState {

  static final S_77 instance = new S_77();

  private S_77() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$7(text, line, pos);
  }
}
