/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_78
    extends FinalState {

  static final S_78 instance = new S_78();

  private S_78() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$8(text, line, pos);
  }
}
