/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_78
    extends TransitionState {

  static final S_78 instance = new S_78();

  private S_78() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__o:
      return S_51.instance;
    default:
      return null;
    }
  }

}
