/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_79
    extends FinalState {

  static final S_79 instance = new S_79();

  private S_79() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$0(text, line, pos);
  }
}
