/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_79
    extends TransitionState {

  static final S_79 instance = new S_79();

  private S_79() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__t:
      return S_121.instance;
    default:
      return null;
    }
  }

}
