/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_8
    extends TransitionState {

  static final S_8 instance = new S_8();

  private S_8() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__A:
      return S_7.instance;
    case Symbol_95:
      return S_8.instance;
    case Symbol__a:
      return S_7.instance;
    case Symbol__b:
      return S_7.instance;
    case Symbol__c:
      return S_7.instance;
    case Symbol__d:
      return S_7.instance;
    case Symbol__e:
      return S_7.instance;
    case Symbol__f:
      return S_7.instance;
    case Symbol__h:
      return S_7.instance;
    case Symbol__i:
      return S_7.instance;
    case Symbol__j:
      return S_7.instance;
    case Symbol__k:
      return S_7.instance;
    case Symbol__l:
      return S_7.instance;
    case Symbol__n:
      return S_7.instance;
    case Symbol__o:
      return S_7.instance;
    case Symbol__p:
      return S_7.instance;
    case Symbol__q:
      return S_7.instance;
    case Symbol__r:
      return S_7.instance;
    case Symbol__s:
      return S_7.instance;
    case Symbol__t:
      return S_7.instance;
    case Symbol__u:
      return S_7.instance;
    case Symbol__v:
      return S_7.instance;
    case Symbol__w:
      return S_7.instance;
    case Symbol__x:
      return S_7.instance;
    case Symbol__z:
      return S_7.instance;
    default:
      return null;
    }
  }

}
