/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_80
    extends TransitionState {

  static final S_80 instance = new S_80();

  private S_80() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__t:
      return S_122.instance;
    default:
      return null;
    }
  }

}
