/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_81
    extends TransitionState {

  static final S_81 instance = new S_81();

  private S_81() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__u:
      return S_123.instance;
    default:
      return null;
    }
  }

}
