/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_82
    extends TransitionState {

  static final S_82 instance = new S_82();

  private S_82() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__o:
      return S_124.instance;
    default:
      return null;
    }
  }

}
