/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_83
    extends FinalState {

  static final S_83 instance = new S_83();

  private S_83() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$30(text, line, pos);
  }
}
