/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_83
    extends TransitionState {

  static final S_83 instance = new S_83();

  private S_83() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__o:
      return S_125.instance;
    default:
      return null;
    }
  }

}
