/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_84
    extends TransitionState {

  static final S_84 instance = new S_84();

  private S_84() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__l:
      return S_126.instance;
    default:
      return null;
    }
  }

}
