/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_85
    extends FinalState {

  static final S_85 instance = new S_85();

  private S_85() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$31(text, line, pos);
  }
}
