/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_85
    extends TransitionState {

  static final S_85 instance = new S_85();

  private S_85() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__a:
      return S_127.instance;
    default:
      return null;
    }
  }

}
