/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_86
    extends TransitionState {

  static final S_86 instance = new S_86();

  private S_86() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__x:
      return S_128.instance;
    default:
      return null;
    }
  }

}
