/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_87
    extends FinalState {

  static final S_87 instance = new S_87();

  private S_87() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$22(text, line, pos);
  }
}
