/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_87
    extends TransitionState {

  static final S_87 instance = new S_87();

  private S_87() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__r:
      return S_129.instance;
    default:
      return null;
    }
  }

}
