/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_89
    extends FinalState {

  static final S_89 instance = new S_89();

  private S_89() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$26(text, line, pos);
  }
}
