/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_9
    extends TransitionState {

  static final S_9 instance = new S_9();

  private S_9() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__a:
      return S_37.instance;
    case Symbol__b:
      return S_38.instance;
    case Symbol__d:
      return S_39.instance;
    case Symbol__f:
      return S_40.instance;
    case Symbol__g:
      return S_41.instance;
    case Symbol__h:
      return S_42.instance;
    case Symbol__s:
      return S_43.instance;
    case Symbol__t:
      return S_44.instance;
    case Symbol__w:
      return S_45.instance;
    default:
      return null;
    }
  }

}
