/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_92
    extends FinalState {

  static final S_92 instance = new S_92();

  private S_92() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$17(text, line, pos);
  }
}
