/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_94
    extends TransitionState {

  static final S_94 instance = new S_94();

  private S_94() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol__o:
      return S_54.instance;
    default:
      return null;
    }
  }

}
