/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_94
    extends FinalState {

  static final S_94 instance = new S_94();

  private S_94() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$35(text, line, pos);
  }
}
