/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_97
    extends FinalState {

  static final S_97 instance = new S_97();

  private S_97() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$4(text, line, pos);
  }
}
