/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

class S_99
    extends FinalState {

  static final S_99 instance = new S_99();

  private S_99() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$6(text, line, pos);
  }
}
