/* This file was generated by SableCC ( http://sablecc.org ). */

package language_emuMips;

public class Walker {

  public void inString(NString node) {
    defaultIn(node);
  }

  public void inNumber(NNumber node) {
    defaultIn(node);
  }

  public void inRegister(NRegister node) {
    defaultIn(node);
  }

  public void inConsoleString(NConsoleString node) {
    defaultIn(node);
  }

  public void inStmts_Many(NStmts_Many node) {
    defaultIn(node);
  }

  public void inStmts_One(NStmts_One node) {
    defaultIn(node);
  }

  public void inStmt_Add(NStmt_Add node) {
    defaultIn(node);
  }

  public void inStmt_Addi(NStmt_Addi node) {
    defaultIn(node);
  }

  public void inStmt_Addu(NStmt_Addu node) {
    defaultIn(node);
  }

  public void inStmt_Addiu(NStmt_Addiu node) {
    defaultIn(node);
  }

  public void inStmt_Sub(NStmt_Sub node) {
    defaultIn(node);
  }

  public void inStmt_Subu(NStmt_Subu node) {
    defaultIn(node);
  }

  public void inStmt_And(NStmt_And node) {
    defaultIn(node);
  }

  public void inStmt_Andi(NStmt_Andi node) {
    defaultIn(node);
  }

  public void inStmt_Or(NStmt_Or node) {
    defaultIn(node);
  }

  public void inStmt_Ori(NStmt_Ori node) {
    defaultIn(node);
  }

  public void inStmt_Nor(NStmt_Nor node) {
    defaultIn(node);
  }

  public void inStmt_Xor(NStmt_Xor node) {
    defaultIn(node);
  }

  public void inStmt_Xori(NStmt_Xori node) {
    defaultIn(node);
  }

  public void inStmt_Slt(NStmt_Slt node) {
    defaultIn(node);
  }

  public void inStmt_Slti(NStmt_Slti node) {
    defaultIn(node);
  }

  public void inStmt_Sltu(NStmt_Sltu node) {
    defaultIn(node);
  }

  public void inStmt_Sltiu(NStmt_Sltiu node) {
    defaultIn(node);
  }

  public void inStmt_Sll(NStmt_Sll node) {
    defaultIn(node);
  }

  public void inStmt_Srl(NStmt_Srl node) {
    defaultIn(node);
  }

  public void inStmt_Beq(NStmt_Beq node) {
    defaultIn(node);
  }

  public void inStmt_Bne(NStmt_Bne node) {
    defaultIn(node);
  }

  public void inStmt_Lbu(NStmt_Lbu node) {
    defaultIn(node);
  }

  public void inStmt_Lb(NStmt_Lb node) {
    defaultIn(node);
  }

  public void inStmt_Lhu(NStmt_Lhu node) {
    defaultIn(node);
  }

  public void inStmt_Ll(NStmt_Ll node) {
    defaultIn(node);
  }

  public void inStmt_Lui(NStmt_Lui node) {
    defaultIn(node);
  }

  public void inStmt_Lh(NStmt_Lh node) {
    defaultIn(node);
  }

  public void inStmt_Lw(NStmt_Lw node) {
    defaultIn(node);
  }

  public void inStmt_Sb(NStmt_Sb node) {
    defaultIn(node);
  }

  public void inStmt_Sc(NStmt_Sc node) {
    defaultIn(node);
  }

  public void inStmt_Sh(NStmt_Sh node) {
    defaultIn(node);
  }

  public void inStmt_Sw(NStmt_Sw node) {
    defaultIn(node);
  }

  public void inStmt_Lbl(NStmt_Lbl node) {
    defaultIn(node);
  }

  public void inStmt_Jmp(NStmt_Jmp node) {
    defaultIn(node);
  }

  public void inStmt_Jmpreg(NStmt_Jmpreg node) {
    defaultIn(node);
  }

  public void inStmt_Jmplnk(NStmt_Jmplnk node) {
    defaultIn(node);
  }

  public void inStmt_Data(NStmt_Data node) {
    defaultIn(node);
  }

  public void inStmt_Text(NStmt_Text node) {
    defaultIn(node);
  }

  public void inStmt_Globl(NStmt_Globl node) {
    defaultIn(node);
  }

  public void inStmt_Syscall(NStmt_Syscall node) {
    defaultIn(node);
  }

  public void inStmt_Mov(NStmt_Mov node) {
    defaultIn(node);
  }

  public void inStmt_La(NStmt_La node) {
    defaultIn(node);
  }

  public void inStmt_Li(NStmt_Li node) {
    defaultIn(node);
  }

  public void inRegExpr(NRegExpr node) {
    defaultIn(node);
  }

  public void inImmExpr(NImmExpr node) {
    defaultIn(node);
  }

  public void inImmExpru(NImmExpru node) {
    defaultIn(node);
  }

  public void inShift(NShift node) {
    defaultIn(node);
  }

  public void inRs(NRs node) {
    defaultIn(node);
  }

  public void inRt(NRt node) {
    defaultIn(node);
  }

  public void inArray(NArray node) {
    defaultIn(node);
  }

  public void inCommonDatas_Many(NCommonDatas_Many node) {
    defaultIn(node);
  }

  public void inCommonDatas_One(NCommonDatas_One node) {
    defaultIn(node);
  }

  public void inRd(NRd node) {
    defaultIn(node);
  }

  public void inCommonData_Word(NCommonData_Word node) {
    defaultIn(node);
  }

  public void inCommonData_Half(NCommonData_Half node) {
    defaultIn(node);
  }

  public void inCommonData_Byte(NCommonData_Byte node) {
    defaultIn(node);
  }

  public void inCommonData_Ascii(NCommonData_Ascii node) {
    defaultIn(node);
  }

  public void inCommonData_Asciiz(NCommonData_Asciiz node) {
    defaultIn(node);
  }

  public void inCommonData_Float(NCommonData_Float node) {
    defaultIn(node);
  }

  public void inCommonData_Double(NCommonData_Double node) {
    defaultIn(node);
  }

  public void inCommonData_Space(NCommonData_Space node) {
    defaultIn(node);
  }

  public void inCommonData_Align(NCommonData_Align node) {
    defaultIn(node);
  }

  public void inCommonData_Lbl(NCommonData_Lbl node) {
    defaultIn(node);
  }

  public void inDirectivesQte_Dirqt(NDirectivesQte_Dirqt node) {
    defaultIn(node);
  }

  public void defaultIn(Node node) {
  }

  public void caseString(NString node) {
    defaultCase(node);
  }

  public void caseNumber(NNumber node) {
    defaultCase(node);
  }

  public void caseRegister(NRegister node) {
    defaultCase(node);
  }

  public void caseConsoleString(NConsoleString node) {
    defaultCase(node);
  }

  public void caseStmts_Many(NStmts_Many node) {
    defaultCase(node);
  }

  public void caseStmts_One(NStmts_One node) {
    defaultCase(node);
  }

  public void caseStmt_Add(NStmt_Add node) {
    defaultCase(node);
  }

  public void caseStmt_Addi(NStmt_Addi node) {
    defaultCase(node);
  }

  public void caseStmt_Addu(NStmt_Addu node) {
    defaultCase(node);
  }

  public void caseStmt_Addiu(NStmt_Addiu node) {
    defaultCase(node);
  }

  public void caseStmt_Sub(NStmt_Sub node) {
    defaultCase(node);
  }

  public void caseStmt_Subu(NStmt_Subu node) {
    defaultCase(node);
  }

  public void caseStmt_And(NStmt_And node) {
    defaultCase(node);
  }

  public void caseStmt_Andi(NStmt_Andi node) {
    defaultCase(node);
  }

  public void caseStmt_Or(NStmt_Or node) {
    defaultCase(node);
  }

  public void caseStmt_Ori(NStmt_Ori node) {
    defaultCase(node);
  }

  public void caseStmt_Nor(NStmt_Nor node) {
    defaultCase(node);
  }

  public void caseStmt_Xor(NStmt_Xor node) {
    defaultCase(node);
  }

  public void caseStmt_Xori(NStmt_Xori node) {
    defaultCase(node);
  }

  public void caseStmt_Slt(NStmt_Slt node) {
    defaultCase(node);
  }

  public void caseStmt_Slti(NStmt_Slti node) {
    defaultCase(node);
  }

  public void caseStmt_Sltu(NStmt_Sltu node) {
    defaultCase(node);
  }

  public void caseStmt_Sltiu(NStmt_Sltiu node) {
    defaultCase(node);
  }

  public void caseStmt_Sll(NStmt_Sll node) {
    defaultCase(node);
  }

  public void caseStmt_Srl(NStmt_Srl node) {
    defaultCase(node);
  }

  public void caseStmt_Beq(NStmt_Beq node) {
    defaultCase(node);
  }

  public void caseStmt_Bne(NStmt_Bne node) {
    defaultCase(node);
  }

  public void caseStmt_Lbu(NStmt_Lbu node) {
    defaultCase(node);
  }

  public void caseStmt_Lb(NStmt_Lb node) {
    defaultCase(node);
  }

  public void caseStmt_Lhu(NStmt_Lhu node) {
    defaultCase(node);
  }

  public void caseStmt_Ll(NStmt_Ll node) {
    defaultCase(node);
  }

  public void caseStmt_Lui(NStmt_Lui node) {
    defaultCase(node);
  }

  public void caseStmt_Lh(NStmt_Lh node) {
    defaultCase(node);
  }

  public void caseStmt_Lw(NStmt_Lw node) {
    defaultCase(node);
  }

  public void caseStmt_Sb(NStmt_Sb node) {
    defaultCase(node);
  }

  public void caseStmt_Sc(NStmt_Sc node) {
    defaultCase(node);
  }

  public void caseStmt_Sh(NStmt_Sh node) {
    defaultCase(node);
  }

  public void caseStmt_Sw(NStmt_Sw node) {
    defaultCase(node);
  }

  public void caseStmt_Lbl(NStmt_Lbl node) {
    defaultCase(node);
  }

  public void caseStmt_Jmp(NStmt_Jmp node) {
    defaultCase(node);
  }

  public void caseStmt_Jmpreg(NStmt_Jmpreg node) {
    defaultCase(node);
  }

  public void caseStmt_Jmplnk(NStmt_Jmplnk node) {
    defaultCase(node);
  }

  public void caseStmt_Data(NStmt_Data node) {
    defaultCase(node);
  }

  public void caseStmt_Text(NStmt_Text node) {
    defaultCase(node);
  }

  public void caseStmt_Globl(NStmt_Globl node) {
    defaultCase(node);
  }

  public void caseStmt_Syscall(NStmt_Syscall node) {
    defaultCase(node);
  }

  public void caseStmt_Mov(NStmt_Mov node) {
    defaultCase(node);
  }

  public void caseStmt_La(NStmt_La node) {
    defaultCase(node);
  }

  public void caseStmt_Li(NStmt_Li node) {
    defaultCase(node);
  }

  public void caseRegExpr(NRegExpr node) {
    defaultCase(node);
  }

  public void caseImmExpr(NImmExpr node) {
    defaultCase(node);
  }

  public void caseImmExpru(NImmExpru node) {
    defaultCase(node);
  }

  public void caseShift(NShift node) {
    defaultCase(node);
  }

  public void caseRs(NRs node) {
    defaultCase(node);
  }

  public void caseRt(NRt node) {
    defaultCase(node);
  }

  public void caseArray(NArray node) {
    defaultCase(node);
  }

  public void caseCommonDatas_Many(NCommonDatas_Many node) {
    defaultCase(node);
  }

  public void caseCommonDatas_One(NCommonDatas_One node) {
    defaultCase(node);
  }

  public void caseRd(NRd node) {
    defaultCase(node);
  }

  public void caseCommonData_Word(NCommonData_Word node) {
    defaultCase(node);
  }

  public void caseCommonData_Half(NCommonData_Half node) {
    defaultCase(node);
  }

  public void caseCommonData_Byte(NCommonData_Byte node) {
    defaultCase(node);
  }

  public void caseCommonData_Ascii(NCommonData_Ascii node) {
    defaultCase(node);
  }

  public void caseCommonData_Asciiz(NCommonData_Asciiz node) {
    defaultCase(node);
  }

  public void caseCommonData_Float(NCommonData_Float node) {
    defaultCase(node);
  }

  public void caseCommonData_Double(NCommonData_Double node) {
    defaultCase(node);
  }

  public void caseCommonData_Space(NCommonData_Space node) {
    defaultCase(node);
  }

  public void caseCommonData_Align(NCommonData_Align node) {
    defaultCase(node);
  }

  public void caseCommonData_Lbl(NCommonData_Lbl node) {
    defaultCase(node);
  }

  public void caseDirectivesQte_Dirqt(NDirectivesQte_Dirqt node) {
    defaultCase(node);
  }

  public void defaultCase(Node node) {
    node.applyOnChildren(this);
  }

  public void outString(NString node) {
    defaultOut(node);
  }

  public void outNumber(NNumber node) {
    defaultOut(node);
  }

  public void outRegister(NRegister node) {
    defaultOut(node);
  }

  public void outConsoleString(NConsoleString node) {
    defaultOut(node);
  }

  public void outStmts_Many(NStmts_Many node) {
    defaultOut(node);
  }

  public void outStmts_One(NStmts_One node) {
    defaultOut(node);
  }

  public void outStmt_Add(NStmt_Add node) {
    defaultOut(node);
  }

  public void outStmt_Addi(NStmt_Addi node) {
    defaultOut(node);
  }

  public void outStmt_Addu(NStmt_Addu node) {
    defaultOut(node);
  }

  public void outStmt_Addiu(NStmt_Addiu node) {
    defaultOut(node);
  }

  public void outStmt_Sub(NStmt_Sub node) {
    defaultOut(node);
  }

  public void outStmt_Subu(NStmt_Subu node) {
    defaultOut(node);
  }

  public void outStmt_And(NStmt_And node) {
    defaultOut(node);
  }

  public void outStmt_Andi(NStmt_Andi node) {
    defaultOut(node);
  }

  public void outStmt_Or(NStmt_Or node) {
    defaultOut(node);
  }

  public void outStmt_Ori(NStmt_Ori node) {
    defaultOut(node);
  }

  public void outStmt_Nor(NStmt_Nor node) {
    defaultOut(node);
  }

  public void outStmt_Xor(NStmt_Xor node) {
    defaultOut(node);
  }

  public void outStmt_Xori(NStmt_Xori node) {
    defaultOut(node);
  }

  public void outStmt_Slt(NStmt_Slt node) {
    defaultOut(node);
  }

  public void outStmt_Slti(NStmt_Slti node) {
    defaultOut(node);
  }

  public void outStmt_Sltu(NStmt_Sltu node) {
    defaultOut(node);
  }

  public void outStmt_Sltiu(NStmt_Sltiu node) {
    defaultOut(node);
  }

  public void outStmt_Sll(NStmt_Sll node) {
    defaultOut(node);
  }

  public void outStmt_Srl(NStmt_Srl node) {
    defaultOut(node);
  }

  public void outStmt_Beq(NStmt_Beq node) {
    defaultOut(node);
  }

  public void outStmt_Bne(NStmt_Bne node) {
    defaultOut(node);
  }

  public void outStmt_Lbu(NStmt_Lbu node) {
    defaultOut(node);
  }

  public void outStmt_Lb(NStmt_Lb node) {
    defaultOut(node);
  }

  public void outStmt_Lhu(NStmt_Lhu node) {
    defaultOut(node);
  }

  public void outStmt_Ll(NStmt_Ll node) {
    defaultOut(node);
  }

  public void outStmt_Lui(NStmt_Lui node) {
    defaultOut(node);
  }

  public void outStmt_Lh(NStmt_Lh node) {
    defaultOut(node);
  }

  public void outStmt_Lw(NStmt_Lw node) {
    defaultOut(node);
  }

  public void outStmt_Sb(NStmt_Sb node) {
    defaultOut(node);
  }

  public void outStmt_Sc(NStmt_Sc node) {
    defaultOut(node);
  }

  public void outStmt_Sh(NStmt_Sh node) {
    defaultOut(node);
  }

  public void outStmt_Sw(NStmt_Sw node) {
    defaultOut(node);
  }

  public void outStmt_Lbl(NStmt_Lbl node) {
    defaultOut(node);
  }

  public void outStmt_Jmp(NStmt_Jmp node) {
    defaultOut(node);
  }

  public void outStmt_Jmpreg(NStmt_Jmpreg node) {
    defaultOut(node);
  }

  public void outStmt_Jmplnk(NStmt_Jmplnk node) {
    defaultOut(node);
  }

  public void outStmt_Data(NStmt_Data node) {
    defaultOut(node);
  }

  public void outStmt_Text(NStmt_Text node) {
    defaultOut(node);
  }

  public void outStmt_Globl(NStmt_Globl node) {
    defaultOut(node);
  }

  public void outStmt_Syscall(NStmt_Syscall node) {
    defaultOut(node);
  }

  public void outStmt_Mov(NStmt_Mov node) {
    defaultOut(node);
  }

  public void outStmt_La(NStmt_La node) {
    defaultOut(node);
  }

  public void outStmt_Li(NStmt_Li node) {
    defaultOut(node);
  }

  public void outRegExpr(NRegExpr node) {
    defaultOut(node);
  }

  public void outImmExpr(NImmExpr node) {
    defaultOut(node);
  }

  public void outImmExpru(NImmExpru node) {
    defaultOut(node);
  }

  public void outShift(NShift node) {
    defaultOut(node);
  }

  public void outRs(NRs node) {
    defaultOut(node);
  }

  public void outRt(NRt node) {
    defaultOut(node);
  }

  public void outArray(NArray node) {
    defaultOut(node);
  }

  public void outCommonDatas_Many(NCommonDatas_Many node) {
    defaultOut(node);
  }

  public void outCommonDatas_One(NCommonDatas_One node) {
    defaultOut(node);
  }

  public void outRd(NRd node) {
    defaultOut(node);
  }

  public void outCommonData_Word(NCommonData_Word node) {
    defaultOut(node);
  }

  public void outCommonData_Half(NCommonData_Half node) {
    defaultOut(node);
  }

  public void outCommonData_Byte(NCommonData_Byte node) {
    defaultOut(node);
  }

  public void outCommonData_Ascii(NCommonData_Ascii node) {
    defaultOut(node);
  }

  public void outCommonData_Asciiz(NCommonData_Asciiz node) {
    defaultOut(node);
  }

  public void outCommonData_Float(NCommonData_Float node) {
    defaultOut(node);
  }

  public void outCommonData_Double(NCommonData_Double node) {
    defaultOut(node);
  }

  public void outCommonData_Space(NCommonData_Space node) {
    defaultOut(node);
  }

  public void outCommonData_Align(NCommonData_Align node) {
    defaultOut(node);
  }

  public void outCommonData_Lbl(NCommonData_Lbl node) {
    defaultOut(node);
  }

  public void outDirectivesQte_Dirqt(NDirectivesQte_Dirqt node) {
    defaultOut(node);
  }

  public void defaultOut(Node node) {
  }
}
